### ISSUE TITLE
SF2 to XPM issue

### ISSUE THREAD

**Issue by bjonnh** [git-moss/ConvertWithMoss#22] opened 2023-09-09 21:46 UTC
I've tried to convert some SF2 such as : 
https://drive.google.com/file/d/1e5nPbx7_yPY6mNr3H1pInUgTKmGM6cHo/view?usp=sharing
(from https://sites.google.com/site/soundfonts4u/ )

For a MPC One. But the sample files are not correct (the next samples seem to be starting right inside the existing samples)
The samples are looping continuously and the panning is set all the way to one side.

I'm using version 6.3.0 from git (revision: https://github.com/git-moss/ConvertWithMoss/commit/44f70d17f51bac009920095843c88f36578e5da6 )

Let me know if you want me to try things out.

**Comment by git-moss** [comment] 2023-09-11 17:20
Thanks for the test file, that helped a lot!

The algorithm always combines mono sample files to stereo files since some formats require that.
I guess you did notice the warnings about the different sample and loop lengths of the left/right channel. I did implement the workaround for this issue blind since I did not have a test file for this.
Seems there was data added to the shorter sample from the following sample (which caused the strange delay effect). It will now simply be padded with silence. What I cannot fix is the different loop start/end but at least with the example that does not matter.
Furthermore, I forgot to adjust the panning which will be fixed in the next update as well.
The example works now fine if I export to SFZ.

I still have issues with MPC. The problem is that there are more layers than keygroups can contain (4) but my workaround / warnings for this seem not to show up, need to look deeper into this...
Also there is a strange never ending loop happening, which so far I have no idea which setting causes this.

**Comment by bjonnh** [comment] 2023-09-11 18:25
Thanks a lot for looking into that. I'll continue digging the MPC part. I noticed the continuous delay thing it is as if the note was never released.

**Comment by git-moss** [comment] 2023-09-11 18:44
If you can find out which parameter causes this, that would be helpful.

**Comment by git-moss** [comment] 2023-09-23 21:40
I just released version 7.0.0 with these fixes. I also added that the loop information is written to the WAV files which seem to be read as well by the MPC software.
The behaviour of the Amplitude envelope is still pretty weird with the Piano example file. The filter envelope seems to behave as expected.

**Comment by bjonnh** [comment] 2023-09-23 22:02
This is great thank you so much, I'll try that!

**Closed** 2023-10-10 12:54 UTC
