### ISSUE TITLE
Stereo samples are falsely identified as L + R split samples

### ISSUE THREAD

**Issue by Loadus** [git-moss/ConvertWithMoss#9] opened 2022-01-24 16:26 UTC
I tried to create an MPC Keygroup program from raw stereo samples, where the files had an identifier for both the layer number and the midi note in the filename. The processing fails with the error 

`Could not create multisample: Attempt to combine Mono splits into Stereo files but not all notes have the same number of files.
Key: 1
* Sample 1: LAYER1_001.wav
* Sample 2: LAYER1_101.wav`

as the app assumes I have L and R mono samples as source.
I tried a different name for the layer tag but the processing still fails.

The files are named LAYERn_m.wav, where n is the layer number (1-4) and m is the MIDI note number (1-128).

**Comment by git-moss** [comment] 2022-01-24 18:22
Try to write "LAYER*_" (without the quotes) in the velocity layer detection field. If this does not work, please send me the files for testing.

**Comment by Loadus** [comment] 2022-01-24 23:42
Here are some template files to test out the filter >> [https://drive.google.com/file/d/11j2eNAZnArvuAHTtna7tU56hX40-gecV/view?usp=sharing](url)

**Comment by git-moss** [comment] 2022-01-25 18:41
Thanks for the files. The issue is that I expect the MIDI note numbers in the range of [0..127] but your files have [1..128].
Did you generate these names yourself or do they come from another tool?

**Comment by Loadus** [comment] 2022-01-25 21:46
0 .. 127 is correct - the example files are quickly renamed in batch just to demonstrate the error, so that's my bad. (The original samples are numbered 0 to 127)

**Comment by git-moss** [comment] 2022-01-26 18:18
When removing the 128 it works fine for me with layer detection set to LAYER*_
Can I close it or do you still have issues?

**Comment by Loadus** [comment] 2022-01-26 21:40
Seems that the core problem was leading zeroes, ie "LAYER1_001.wav" compared to "LAYER1_1.wav". Though it does throw an error >>
`Could not create multisample: Could not detect MIDI note in file name: _99.wav`
But you can close this issue as it's not the same error.

**Comment by git-moss** [comment] 2022-01-27 17:09
Just release 4.7, which should now detect leading zeroes as well.

**Closed by git-moss** 2022-01-27 17:09 UTC
